### ISSUE TITLE
[BUG] - Typo Bij 'Hulp Nodig?'

### ISSUE THREAD

**Issue by Pieter-Beckers** [milieuinfo/webcomponent-vl-ui-header#39]
**Omschrijf het probleem**
In de header bij 'HULP NODIG?' komt 'de Departement Omgeving', ik zou hier 'het Departement Omgeving' verwachten of het lidwoord weglaten

**Hoe te reproduceren**
Maak een header, en klik op 'HULP NODIG?' rechts bovenaan.

**Gewenst gedrag**
typo fixen

**Screenshots**
![image](https://user-images.githubusercontent.com/28813026/98231181-5f39ae00-1f5c-11eb-8fcc-dfa4634b64a1.png)

**Omgeving (gelieve aan te vullen):**
 - Browser Chrome

**Extra info**
Extra context omtrent het probleem.

**Comment by coemans** [comment]
@Pieter-Beckers het probleem zou centraal opgelost zijn.
